### ISSUE TITLE
flattenObject is broken

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/utils#6]
https://github.com/jillix/utils/blob/2c2a0a3990d7b33729b82432d8e1459f2a844e58/utils.js#L64

**Comment by gabipetrovay** [comment]
Where?

**Comment by IonicaBizau** [comment]
[Shame on me](https://github.com/jillix/utils/commit/6d170a76230b4140412f7efdbbad43b5e40f1a6c).

We have the luck we didn't update the Bind and the Events modules with the latest version. :smile:

**Comment by danandrei** [comment]
This was fixed in https://github.com/jillix/utils/commit/2be1f95bb7c744bc620b06107fba216ff509e9b0

**Comment by IonicaBizau** [comment]
:+1: Published 0.1.8 on NPM.
